completed the project
mahmoud717/embedding-video-images pull request #1
Opened 2020-07-09 15:56 UTC by mahmoud717

2020-07-09 16:29 UTC, expjazz requested changes
## Hey @mahmoud717 and @Adewunmi97 

#### There are a few problems with the repo. Here is what you need to change:

- The readme file has no content. You can check more here: https://github.com/microverseinc/readme-template

- The pull request does not have a meaningful title and neither a description. Kindly add them for the next review.

- You should commit more often

#### For more info on these subjects, check this link: https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

### This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready! :pray:

Good Luck and Happy Coding :+1: :

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

2020-07-10 09:44 UTC, HADDADSOHAIB requested changes
### Status: Change required :recycle: 

### Hi @mahmoud717  and @Adewunmi97 

### You did great with the project, good job :+1: . There is some changes that have to be made   to approve the project:
- The recommended video section needs improvement:

| Source Page	| Clone Page |
|:---:|:---:|
|![Screenshot from 2020-07-10 10-30-36](https://user-images.githubusercontent.com/26064042/87139849-7a3f2e80-c298-11ea-9c03-28f4bfd34b53.png) | ![Screenshot from 2020-07-10 10-30-23](https://user-images.githubusercontent.com/26064042/87139912-94790c80-c298-11ea-8500-028d01e8d3ac.png) |

- check my comments for additional requirements.
- In the project description, there was a link that you should have used to build your project:
![image](https://user-images.githubusercontent.com/26064042/87140678-cf2f7480-c299-11ea-8a7f-90c8b7b99024.png)
http://archive.vn/Bss88
there a slight different between your project and that link in the section under the main video.
- [Optional] use  the [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links
- [Optional]  use  the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document

### Once done with the changes, please ask for another code review.

2020-07-10 09:44 UTC, HADDADSOHAIB commented on index.html
> +              <li><i class="fas fa-share"></i> SHARE</li>
The share should be a button
- [ ] It has a share button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

2020-07-10 17:02 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @mahmoud717  and @Adewunmi97! 👋 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There is just one issue that needs to be resolved before you can move on: ⬇️ 
****

- [ ] Please make sure to delete commented code. It is bad practice to leave commented code in your projects as it makes it look untidy. If you need to see a previous version of your code you can do so using your GitHub commit history. Please see my comments for instances of commented code in your files. 

- [ ] Please check my comments for additional changes. 

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-07-10 17:02 UTC, BrittanyBlake commented on index.html
> +            </div> -->
Please remove commented code .

2020-07-10 17:03 UTC, BrittanyBlake commented on styles.css
> +} */
Please remove commented code .

2020-07-10 17:05 UTC, BrittanyBlake commented on styles.css
> +  padding-left: 0px !important;
Try not to use `!important` in your code. If you need to override something you can do so using selector specificity.  You can learn more about that in [this article](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) and in [this article](https://www.w3schools.com/css/css_specificity.asp)

2020-07-10 18:13 UTC, ikraamg commented
### **Status: PROJECT APPROVED**  :1st_place_medal: :1st_place_medal: :1st_place_medal:


Hi @Adewunmi97  and @mahmoud717  :smile:  Congratulations, your project looks amazing and you did an amazing job improving it and making the necessary changes :sunglasses:. I know it's been a long journey and you should be proud of yourself for pushing it through!  

You can merge and submit your project! 

**A little hint that is sometimes useful:** 
When you want to stop your site from breaking when too small or looking odd on big screens, you can apply the following css code on your **html or body** tag of your page:
_min-width: 350px;_ (you can pick your pixels)
_max-width: 1366px;_ (you can pick your pixels)

If you have any questions, don't hesitate to contact me through slack: **_@ikraam_**


_**Happy coding and good luck on the next project**_  :desktop_computer: 

_Project reviewed by Ikraam Ghoor (TSE)_

2020-07-10 19:22 UTC, merged